spring:
  application:
    name: technical-test-api
  main:
    web-application-type: servlet
  data:
    mongodb:
      database: auchan-tech-test

springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /

logging.level.tomcat: TRACE

server:
  port: 8086